[package]
name = "ffi-checker"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cargo-ffi-checker"

[dependencies]
pretty_env_logger = "0.5.0"
log = "0.4.22"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
